<?php

function generateBodyContratoAhorro($nombreSocia, $empresa, $direccion, $fecha, $sucursalDireccion)
{

    $html = '
    <h3 align="center">CONTRATO DE DEPÓSITO DE DINERO PARA OPERACIONES EN CUENTA DE AHORROS</h3>

    <p>QUE CELEBRAN, POR UNA PARTE, ' . $nombreSocia . ', A QUIEN EN LO SUCESIVO SE LE DESIGNARÁ COMO “EL SOCIO”, Y POR OTRA PARTE “' . $empresa . '” REPRESENTADA EN ESTE ACTO POR EL C. NICANDRO VASQUEZ RUIZ, EN SU CARÁCTER DE REPRESENTANTE LEGAL A QUIEN EN LO SUCESIVO SE LLAMARÁ “LA SOCIEDAD”, DE CONFORMIDAD CON LAS SIGUIENTES:</p>

    <h4 align="center">CLÁUSULAS</h4>
    
    <p><b>PRIMERA. </b>El objeto del presente Contrato de Depósito de Dinero para operaciones a la vista en cuenta de ahorros es establecer los lineamientos en virtud de los cuales “' . $empresa . '” ofrecerá al Socio el servicio de depósito a la vista. El Socio podrá consignar, a través de los mecanismos que más adelante se establecen, diversas cantidades de dinero que, de conformidad con lo establecido en la fracción I del Artículo 32 de la Ley de Ahorro y Crédito Popular, serán recibidas por ' . $empresa . ' en calidad de depósito de  ahorro. El Socio podrá llevar a cabo, en días y horas hábiles para ' . $empresa . ', las operaciones que se enlistan a continuación (en lo sucesivo denominadas como “Los Servicios”):</p>

    <ol type="a">
        <li>Efectuar depósitos de dinero a la vista.</li>
        <li>Efectuar retiros de dinero, con cargo a su Saldo o Saldos Disponibles.</li>
        <li>Solicitar consultas de sus movimientos o Saldo Disponible en las sucursales y oficinas de la Sociedad.</li>
        <li>Solicitar traspasos a Operaciones de Inversión; y,</li>
        <li>Acceder a aquellos servicios adicionales que la Sociedad establezca en beneficio de El Socio.</li>
    </ol>

    <p><b>SEGUNDA. </b>El Socio tiene acceso a Los Servicios en virtud de la aportación de capital que ha sido realizada en La Sociedad.</p>

    <p><b>TERCERA. </b>Todos Los Servicios que ejecute El Socio se llevarán a cabo exclusivamente mediante su número de Socio, que funcionará como cuenta universal, sobre la cual podrán asignarse tantas cuentas a la vista como El Socio desee aperturar (en lo sucesivo denominado como “Número de Socio”).</p>

    <p><b>CUARTA. </b>Todos los accesos a Los Servicios que se ofrecen en virtud de este Contrato se llevarán a cabo por instrucciones expresas de El Socio. Estas instrucciones podrán entregarse en las oficinas de la Sociedad, mediante el envío de un fax, a través de un correo electrónico o mediante instrucciones telefónicas. Previo a cualquier transacción, se requerirá la identificación por parte de la Sociedad, que incluirá su Número en la Sociedad y su número de cuenta. Asimismo, utilizando su Número de Socio, El Socio podrá indicar, en cualquier momento, el número de las cuentas en Intermediarios Financieros debidamente autorizados conforme a los ordenamientos legales aplicables (en lo sucesivo "La Sociedad"). Estas cuentas podrán recibir depósitos sobre Saldos Disponibles de dinero a la vista, dejando en todo caso constancia escrita de esta autorización.</p>

    <p><b>QUINTA. </b>Para efectos de este Contrato, se entenderá por Saldo Disponible la suma de los depósitos más los intereses que devenguen los mismos, menos los retiros, las comisiones, los gastos generados y los impuestos retenidos que se causen en cada una de las cuentas (en lo sucesivo "Saldos Disponibles").</p>

    <p><b>SEXTA. </b>El Socio podrá autorizar a una o varias personas para que, en su nombre y representación y con el carácter de mandatarios, hagan uso de Los Servicios que fueran necesarios en sus números de cuenta con su Número de Socio (en lo sucesivo, “Las Personas Autorizadas”).</p>

    <p><b>SÉPTIMA. </b>El Socio se hace responsable del buen uso que se dé a su Número de Socio, y al número de las cuentas que la Sociedad le proporcione, por lo cual, serán responsabilidad de El Socio cualesquiera operaciones que se autoricen al amparo de estas claves por El Socio o por Las Personas Autorizadas.</p>

    <p><b>OCTAVA. </b>La Sociedad tendrá la facultad de determinar libremente los montos mínimos a partir de los cuales esté dispuesta a recibir y documentar depósitos de dinero a la vista, así como los importes a partir de los cuales se devengarán intereses a favor de El Socio.</p>

    <p><b>NOVENA. </b>Los depósitos realizados por El Socio, definidos en Los Servicios, deberán ser efectuados en Moneda Nacional. La Sociedad restituirá las sumas prestadas en la misma moneda, conforme a la Ley Monetaria vigente en la República Mexicana al momento de efectuar el pago. Dicha restitución consistirá en una cantidad igual a la recibida, más los intereses generados en su caso, menos las comisiones, gastos, retenciones de impuestos u otras erogaciones que se hubieren realizado.</p>   
    
    <p>La Sociedad podrá efectuar los pagos mediante efectivo, cheque nominativo o depósito en cuenta en cualquier Institución autorizada por El Socio, de conformidad con los acuerdos establecidos en el presente contrato. En caso de que El Socio prefiera que los pagos se realicen a través de depósito en alguna cuenta girada a su favor en alguna Institución, las partes acuerdan que dicho depósito sea realizado por la Sociedad en alguna de las cuentas referidas en la Relación de Bancos y Números de Cuenta del Socio.</p>

    <p><b>DÉCIMA. </b>La Sociedad únicamente recibirá en depósito las cantidades que se entreguen en los días y horas laborales en las  oficinas de la Sociedad o a través de sus sucursales, o cuando El Socio realice depósitos en las cuentas de cheques indicadas por la Sociedad, y de las cuáles la Sociedad sea titular. En  caso de que El Socio desee girar cheques a nombre de la Sociedad para depósito en las cuentas a nombre de El Socio, dichos cheques deben estar expedidos a nombre de ' . $empresa . ' En ningún caso, la Sociedad será responsable sobre depósitos que El Socio o Las Personas Autorizadas realicen en una cuenta donde la Sociedad, no sea titular.</p>

    <p><b>DÉCIMA  PRIMERA. </b>La  Sociedad abonará a las cuentas a nombre de El Socio los  depósitos que el mismo realice en días hábiles de lunes a viernes, de 9:00 a 15:30 hrs, en la misma fecha del depósito. Los depósitos realizados con posterioridad a esa hora se entenderán como realizados en el día hábil siguiente.</p>

    <p><b>DÉCIMA  SEGUNDA. </b>Las sumas que El Socio mantenga depositadas en sus cuentas  generarán intereses, los cuales se calcularán aplicando la tasa de interés vigente determinada por la Sociedad, y serán acreditados en los propios números de cuenta de El Socio por mensualidades vencidas.</p>

    <p><b>DÉCIMA  TERCERA. </b>Los porcentajes de interés se aplicarán de acuerdo al rango en que se encuentre el saldo promedio diario mensual que El Socio mantenga durante el periodo  correspondiente. Los intereses se calcularán dividiendo la suma del Saldo Disponible diario del mes correspondiente, entre el número de días de dicho mes, valor que será multiplicado por el resultado de la división de la tasa de interés anual convenida, entre 360 y finalmente ese valor será multiplicado por el número de días del mes correspondiente.</p>

    <p><b>DÉCIMA  CUARTA. </b>El monto de los intereses, la tasa aplicada y los saldos correspondientes serán dados a conocer en el documento impreso donde se haga constar la operación, o en el estado de cuenta respectivo, donde podrán ser revisados por El Socio. La Sociedad, se reserva el derecho de revisar y ajustar la tasa de interés y los rangos para los saldos promedio diarios. La tasa de interés aplicable será comunicada por la Sociedad mediante la página electrónica que la Sociedad tenga disponible en Internet, en carteles, tableros o pizarrones visibles de manera destacada en los lugares abiertos al público en las oficinas de la Sociedad.</p>

    <p><b>DÉCIMA  QUINTA. </b>Los intereses se generarán a partir del día en que los depósitos  de El Socio se abonen en su Cuenta y hasta el día anterior a aquel en el que se efectúen los retiros. Los intereses se calcularán mensualmente conforme a lo establecido en las cláusulas anteriores, y pasarán a formar parte del Saldo Disponible de cada cuenta al  primer día hábil del mes siguiente al que se calculen.</p>

    <p><b>DÉCIMA SEXTA. </b>Para realizar retiros y recibir el Saldo Disponible, las partes acuerdan que:</p> 

    <ol>
        <li>Montos menores a una suma equivalente a 200 (Doscientos) salarios mínimos diarios generales vigentes para el Estado de Oaxaca se entregarán en efectivo en uno o varios movimientos el mismo día.</li>
        <li>Cantidades superiores podrán retirarse mediante cheque nominativo a favor de El Socio, Las Personas Autorizadas o un tercero.</li>
        <li>En alternativa, el retiro puede efectuarse mediante el depósito en la cuenta bancaria de El Socio, Las Personas Autorizadas o un tercero.</li>
    </ol>

    <p>En caso de que el cheque nominativo se expida, o el depósito de los recursos se transfiera a favor de alguna de las Personas Autorizadas o de un Tercero, El Socio o en su caso alguna de Las Personas Autorizadas, deberán solicitar por escrito a la Sociedad dicha gestión señalando el nombre completo del beneficiario y en su caso el número de cuenta, número de sucursal y nombre de la Institución Sociedad donde se depositarán los recursos. En consecuencia, si El Socio o Las Personas Autorizadas no solicitan por escrito la gestión referida, se entenderá que el cheque nominativo se expedirá a nombre del Socio, o el depósito de los recursos se realizará en el primer número de cuenta señalado por el Socio.</p>

    <p>De acuerdo a lo convenido en el presente Contrato, surtirá efectos de prueba plena para la entrega de los recursos depositados, la ficha de depósito o del traspaso electrónico de dichos fondos de las cuentas de la Sociedad, a las cuentas de El Socio o a las cuentas que El Socio o alguna de Las Personas Autorizadas por escrito soliciten depositar en alguna cuenta a nombre de Las Personas Autorizadas o de un tercero en cualquier Institución Sociedad, o en su caso la firma de El Socio o de alguna de Las Personas Autorizadas o de un tercero en que se dé por recibido del dinero o del cheque nominativo respectivo que ampara la entrega de los fondos solicitados. La Sociedad se reserva el derecho de rehusar el retiro solicitado, si en la cuenta de El Socio no existiera Saldo Disponible suficiente.</p>

    <p><b>DÉCIMA SÉPTIMA. </b>En los términos de las disposiciones legales aplicables, la Sociedad deducirá, retendrá y enterará de la tasa bruta de interés, el impuesto que corresponda a El Socio por las operaciones efectuadas al amparo de este Contrato, por lo que invariablemente entregará a El Socio los rendimientos netos. De igual forma, la Sociedad, trasladará o repercutirá a El Socio cualquier contribución que se cause en los términos de la legislación que resulte aplicable.</p>

    <p><b>DÉCIMA OCTAVA. </b>La Sociedad queda facultada por El Socio, con la firma del presente contrato, a cargar en su cuenta todos los gastos, comisiones, retenciones de impuestos o cualquier adeudo que se genere a cargo de El Socio en relación con este Contrato. Los cargos se harán con efectos a partir de la fecha en que dicho gasto, comisión, retención o adeudo se genere.</p>

    <p><b>DÉCIMA NOVENA. </b>En caso de que la solicitud de disposición de recursos en los números de cuenta de El Socio, requeridos por El Socio o por alguna de Las Personas Autorizadas sea incumplida por la Sociedad, La Sociedad no será responsable cuando el incumplimiento se haya debido a caso fortuito, a fuerza mayor, o a eventos tales como fallas en el funcionamiento de los sistemas de cómputo de la Institución Sociedad donde El Socio o alguna de Las Personas Autorizadas deseen que se depositen los recursos, o en virtud de cualquier tipo de interrupción en los sistemas de comunicación con dicha Institución Sociedad, o por cualquier acontecimiento similar que no se encuentre en posibilidad de resolver o esté fuera de control de la Sociedad.</p>

    <p><b>VIGÉSIMA. </b>Los porcentajes de pago de intereses, las comisiones o el importe de los cobros que por cualquier concepto deban efectuarse, podrán ser modificados de acuerdo a las disposiciones que expidan la Secretaría de Hacienda y Crédito Público, la Comisión Nacional bancaria y de Valores o el Banco de México, o según las políticas internas de la Sociedad, y podrán efectuarse en forma automática en los números de cuenta que la Sociedad, aperture a nombre de El Socio.</p>

    <p><b>VIGÉSIMA PRIMERA. </b>El Socio nombra como beneficiarios de las cuentas que amparan su Número de Socio a las personas mencionadas con este carácter en la Relación de Beneficiarios. Sin embargo El Socio podrá en todo tiempo, designar o sustituir beneficiarios, o modificar la proporción que corresponda a los que hubiera designado mediante notificación por escrito dirigida a la Sociedad. En caso de fallecimiento de El Socio, la Sociedad entregará a los beneficiarios el importe que El Socio haya designado expresamente y por escrito para cada uno de ellos, en caso de que exista Saldo Disponible.</p>

    <p><b>VIGÉSIMA SEGUNDA. </b>Las entregas de dinero que se hagan a La Sociedad por medio de documentos, serán recibidas “salvo buen cobro” y su importe se abonará en firme únicamente al efectuarse su cobro, aún cuando los documentos aparezcan como recibidos por La Sociedad en fecha anterior al abono en firme.</p>

    <p><b>VIGÉSIMA TERCERA. </b>La Sociedad remitirá únicamente a petición expresa y por escrito de El Socio, dentro de los primeros 5 (cinco) días naturales de cada mes, un estado de cuenta en el que se especificarán las cantidades abonadas o cargadas; el saldo al inicio del periodo y a la fecha de corte; el rendimiento bruto y neto obtenidos; y en su caso, el importe de las comisiones a cargo de El Socio durante el período anterior. La fecha de corte para el estado de cuenta, será el último día de cada mes. La Sociedad prevendrá por escrito a El Socio de la fecha de corte, la que no podrá variar sin previo aviso por escrito comunicado por lo menos con un mes de anticipación. La Sociedad quedará relevada del envío a El Socio del estado de cuenta, cuando no haya tenido movimiento alguno durante el periodo respectivo, cuando durante el periodo, el promedio diario del Saldo Disponible haya sido inferior a la suma de 500 (quinientos) salarios mínimos diarios generales para el Estado de Oaxaca, o cuando El Socio no haya manifestado su deseo, por escrito, de recibirlos. De la misma manera La Sociedad quedará relevada de la obligación de enviar el estado de cuenta cuando le proporcione a El Socio la información a través de otros medios impresos.</p>

    <p><b>VIGÉSIMA CUARTA. </b>El Socio se obliga a revisar las operaciones consignadas en su estado de cuenta o en el documento impreso que le entregue La Sociedad, debiendo realizar las observaciones que estime convenientes. En su caso, para poder objetar en tiempo, El Socio deberá de pedir a La Sociedad su estado de cuenta mensual o la información de los movimientos de su cuenta a través de otros medios impresos, dentro de los 5 (cinco) días naturales que sigan al corte. Se presumirá que El Socio recibió dicho estado de cuenta o la información de movimientos a través de otro medio impreso, si no lo reclamare por escrito en dicho plazo. Durante los 15 (quince) días naturales al corte de la cuenta o los 5 (cinco) días hábiles siguientes de haberlo recibido, El Socio podrá manifestar por escrito las objeciones u observaciones que considere procedentes, transcurrido el plazo aquí convenido, las operaciones registradas en el estado de cuenta o en otros medios impresos se considerarán como válidas y correctas, y harán fe salvo prueba en contrario, en el juicio respectivo.</p>

    <p><b>VIGÉSIMA QUINTA. </b>Con excepción de los casos previstos por la ley, La Sociedad no podrá dar noticias o proporcionar información sobre los movimientos operados, el estado que guarde la cuenta de El Socio, o las operaciones que a su amparo se realicen, sino únicamente a El Socio, a sus representantes legales, o a Las Personas Autorizadas. Sin embargo, El Socio expresamente faculta a La Sociedad para realizar, en todo momento investigaciones y proporcionar reportes o información a los organismos de supervisión que La Sociedad tuviere, o a las Sociedades de Información Crediticia que fueran autorizadas por la Secretaría de Hacienda y Crédito Público, acerca de las operaciones celebradas entre La Sociedad y El Socio, el cual manifiesta que conoce la naturaleza y el alcance de la información que se solicitará o proporcionará.</p>

    <p><b>VIGÉSIMA SEXTA. </b>El presente contrato podrá ser modificado por La Sociedad, bastando para ello que lo notifique por escrito a El Socio, por lo menos con 10 (diez) días hábiles de anticipación, a través de los métodos establecidos en la Cláusula Trigésima Tercera de este contrato. Estas modificaciones se entenderán como aceptadas tácitamente por El Socio al momento en que El Socio o alguna de Las Personas Autorizadas realicen cualquier movimiento, giren cualquier instrucción a La Sociedad o hagan uso de cualquiera de Los Servicios en alguno de los números de cuenta de El Socio o en nuevos números de cuenta que deseen aperturar con el Número de Socio.</p>

    <p><b>VIGÉSIMA SÉPTIMA. </b>El presente Contrato podrá darse por terminado por cualquiera de las partes, previo aviso dado por escrito a la otra parte, con 15 (quince) días naturales de anticipación. No obstante la terminación del presente contrato, éste seguirá produciendo todos sus efectos legales entre las partes, hasta que El Socio y la Sociedad hayan cumplido con todas y cada una de las obligaciones contraídas al amparo de este contrato.</p>

    <p><b>VIGÉSIMA OCTAVA. </b>En caso de que El Socio resuelva terminar el presente Contrato, deberá instruir a la Sociedad por escrito acerca de la forma de disposición de los valores o efectivo que existieran a su favor, y en todo caso, deberá liquidar previamente todos los saldos a su cargo. La Sociedad no podrá ser desposeído de los recursos propiedad de El Socio sin que antes haya pagado íntegramente dichos saldos.</p>

    <p><b>VIGÉSIMA NOVENA. </b>En caso de que La Sociedad decida dar por terminado este contrato, una vez que El Socio haya pagado los saldos referidos en la Cláusula anterior, El Socio queda obligado a retirar la totalidad del Saldo Disponible a su favor dentro de los 15 (quince) días hábiles siguientes a la fecha del aviso respectivo. En caso contrario, la Sociedad queda facultada para rembolsar dicho Saldo Disponible en un cheque a nombre de El Socio, mismo que ya no generará intereses a partir de dicha fecha.</p>

    <p><b>TRIGÉSIMA. </b>El incumplimiento por parte de El Socio a cualesquiera de los términos de este Contrato dará derecho a La Sociedad a su inmediata rescisión, independientemente de que pueda exigir el pago de daños y perjuicios derivados de dicho incumplimiento expidiendo en ese momento un cheque a nombre de El Socio por la cantidad del Saldo Disponible en sus cuentas al amparo de su Número de Socio, cuentas que no generarán intereses a partir de dicha fecha.</p>

    <p><b>TRIGÉSIMA PRIMERA. </b>Las partes están de acuerdo en que los anexos al presente Contrato de Depósito, sus adiciones y reformas forman parte integrante del contenido del mismo y su contenido es vinculante y obligatorio para ambos.</p>

    <p><b>TRIGÉSIMA SEGUNDA. </b>Para todos los efectos judiciales y extrajudiciales, El Socio señala como su domicilio ' . $direccion . ' y la Sociedad señala como su domicilio, RAYÓN #704, BARRIO SAN ANTONIO, ZIMATLÁN DE ÁLVAREZ, OAXACA, C.P. 71200.</p>

    <p>Mientras las partes no se notifiquen por escrito el cambio de domicilio, todos los avisos, notificaciones, diligencias que se realicen en el aquí señalado, se tendrán por válidos y surtirán todos los efectos legales que correspondan.</p>

    <p><b>TRIGÉSIMA TERCERA. </b>Las partes convienen en que La Sociedad podrá realizar cualquier notificación a El Socio a través del estado de cuenta, otros medios impresos, publicaciones colocadas en las oficinas de La Sociedad o por cualquier otro medio de divulgación o mediante notificación entregada a El Socio en alguna sucursal de La Sociedad o en su domicilio.</p>

    <p><b>TRIGÉSIMA CUARTA. </b>Para la interpretación y cumplimiento del presente Contrato, las partes se someten expresamente a la competencia de las leyes y a la jurisdicción del Estado de Oaxaca, independientemente de cualquier fuero que pudiera corresponderles en virtud de sus domicilios presentes y futuros. Expuesto lo anterior las partes firman este Contrato con fecha ' . $fecha . ' en ' . $sucursalDireccion . '.</p>
    
    <p>Ratifico tener conocimiento del clausulado y sus implicaciones en cuanto a riesgo, rendimiento y plazo resultantes de mis inversiones así como de la forma en que he quedado clasificado en sus archivos para efectos de mi régimen fiscal, así mismo ratifico que el (los) movimiento (s) que se efectúen, serán con dinero producto del desarrollo normal de la (s) actividad (es) propia (s) y que por tanto no provienen de la realización de actividades ilícitas, por lo que reconozco plenamente conocer y entender las disposiciones relativas a las operaciones realizadas con recursos de procedencia ilícita y sus consecuencias.</p>
    ';

    return $html;
}